PADV 554 - MFE URLs site aware.
Pearson-Advance/edx-platform pull request #102
Opened 2023-06-16 19:12 UTC by alexjmpb

## Ticket

https://agile-jira.pearson.com/browse/PADV-554

## Description

This PR aims to make all the URLs that are related to all the currently active MFEs (learning, discussions, gradebook, profile and account) site aware. It adds a configuration_helpers.get_value to every MFE URL so it can get the value from site configuration.

## Type of Change

- [x] Change occurrences of LEARNING_MICROFRONTEND_URL so it gets the value from site configuration
- [x] Change occurrences of DISCUSSIONS_MICROFRONTEND_URL so it gets the value from site configuration
- [x] Change occurrences of WRITABLE_GRADEBOOK_URL so it gets the value from site configuration
- [x] Change occurrences of PROFILE_MICROFRONTEND_URL so it gets the value from site configuration
- [x] Change occurrences of ACCOUNT_MICROFRONTEND_URL so it gets the value from site configuration

## How to test

- Checkout edx-platform to this branch
- Create a site and a site configuration containing the name of the setting as a key and the url as the value. Like this:
```    "LEARNING_MICROFRONTEND_URL": "http://site1.learningtest.test",
    "WRITABLE_GRADEBOOK_URL": "http://site1.gradebooktest.test",
    "PROFILE_MICROFRONTEND_URL": "http://site1.profiletest.test",
    "ACCOUNT_MICROFRONTEND_URL": "http://site1.accounttest.test",
    "DISCUSSIONS_MICROFRONTEND_URL": "http://site1.discussiontest.test"
```
- In the site, test that whenever you click on a link that should redirect to one of the MFEs, it redirects to the configured URL.

If you want to test each feature in detail, you can search in the edx-platform for the setting name, see where is being used and test that specific feature.

## Reviewers

- [ ] @Squirrel18   
- [ ] @anfbermudezme 
- [ ] @sergivalero20

2023-06-16 21:04 UTC, anfbermudezme requested changes

2023-06-16 21:04 UTC, anfbermudezme commented on openedx/core/djangoapps/user_api/accounts/settings_views.py
> +        url = configuration_helpers.get_value('ACCOUNT_MICROFRONTEND_URL', settings.ACCOUNT_MICROFRONTEND_URL)
Line too long.

2023-06-16 21:04 UTC, anfbermudezme commented on openedx/features/learner_profile/views/learner_profile.py
> +        profile_microfrontend_url = f"{configuration_helpers.get_value('PROFILE_MICROFRONTEND_URL', settings.PROFILE_MICROFRONTEND_URL)}{username}"
Line too long.

2023-06-16 21:04 UTC, anfbermudezme commented on openedx/features/course_experience/url_helpers.py
> +    url = urlparse(configuration_helpers.get_value("LEARNING_MICROFRONTEND_URL", settings.LEARNING_MICROFRONTEND_URL))
Line too long.

2023-06-16 21:04 UTC, anfbermudezme commented on openedx/features/course_experience/url_helpers.py
> +    mfe_link = f'{configuration_helpers.get_value("LEARNING_MICROFRONTEND_URL", settings.LEARNING_MICROFRONTEND_URL)}/course/{course_key}'
Line too long.

2023-06-16 21:04 UTC, anfbermudezme commented on openedx/features/course_experience/url_helpers.py
> +    mfe_link = f'{configuration_helpers.get_value("LEARNING_MICROFRONTEND_URL", settings.LEARNING_MICROFRONTEND_URL)}/course/{course_key}'
Line too long.

2023-06-20 14:53 UTC, sergivalero20 approved these changes

2023-06-20 15:19 UTC, anfbermudezme requested changes

2023-06-20 15:38 UTC, anfbermudezme approved these changes

2023-06-21 00:02 UTC, Squirrel18 approved these changes

2023-06-21 00:06 UTC, merged