PADV-806: feat!: add new content authoring event signals
Pearson-Advance/edx-platform pull request #108
Opened 2023-11-16 21:23 UTC by JuanDavidBuitrago

2023-11-24 22:08 UTC, Jacatove reviewed
@JuanDavidBuitrago Do we really need to back port all content authoring event signals?.
For me it is clear the need to do it for COURSE_CREATED, but I don't know about the others.

2023-11-25 15:59 UTC, anfbermudezme requested changes

2023-11-25 15:59 UTC, anfbermudezme commented on openedx/core/djangoapps/content_libraries/api.py
> +            usage_key=usage_key
Trailing comma. Review the other modules.

2023-11-25 15:59 UTC, anfbermudezme commented on xmodule/modulestore/tests/test_mixed_modulestore.py
> +        event_receiver = Mock()
Add blank line.

2023-11-25 15:59 UTC, anfbermudezme commented on xmodule/modulestore/tests/test_mixed_modulestore.py
> +        self.store.publish(sequential.location, self.user_id)
Add blank line. We follow the structure proposed in https://3.basecamp.com/3966315/buckets/12732851/documents/2737536654. As a summary we divide the tests in three blocks. mock things, call things and assert things.

2023-11-25 15:59 UTC, anfbermudezme commented on xmodule/modulestore/tests/test_mixed_modulestore.py
> +    XBLOCK_UPDATED
Trailing comma.

2023-11-25 15:59 UTC, anfbermudezme commented on xmodule/modulestore/mixed.py
> +        # .. event_implemented_name: XBLOCK_PUBLISHED
Why do you think this inline commets are necessary?

2023-11-25 15:59 UTC, anfbermudezme commented on xmodule/modulestore/mixed.py
> +    XBLOCK_UPDATED
Trailing comma.

2023-11-25 15:59 UTC, anfbermudezme commented on xmodule/modulestore/tests/test_mixed_modulestore.py
>          assert {'course', 'about'}.issubset({item.location.block_type for item in items})  # pylint: disable=line-too-long
```suggestion
        assert {'course', 'about'}.issubset(
           {item.location.block_type for item in items}
        )
```

2023-11-25 15:59 UTC, anfbermudezme commented on xmodule/modulestore/tests/test_mixed_modulestore.py
>          assert [item.location.block_type for item in items if item.location.block_type == 'about'][0]\
```suggestion
        assert [
            item.location.block_type for item in items if item.location.block_type == 'about'
        ][0] in **DETACHED_XBLOCK_TYPES**
```

2023-11-25 15:59 UTC, anfbermudezme commented on openedx/core/djangoapps/content_libraries/tests/test_content_libraries.py
>              assert len(self._get_library_blocks(lib['id'], {'text_search': 'Baz', 'block_type': ['video', 'html']})) ==\
Review indentation please.

2023-11-27 13:10 UTC, JuanDavidBuitrago commented
> @JuanDavidBuitrago Do we really need to back port all content authoring event signals?. For me it is clear the need to do it for COURSE_CREATED, but I don't know about the others.

I added the complete content authoring event signals because I had to update the [openedx-events](https://github.com/openedx/openedx-events/pull/244) [version](https://github.com/Pearson-Advance/edx-platform/pull/108/files#diff-160eb30f60d519b8fe8a919cb2646a7ebec7652952129cfdd803776e70be6300R762), so I consider it is better to implement all of them to avoid problem using that version.

2023-11-27 22:08 UTC, JuanDavidBuitrago commented
I will let it as a draft to future work if it's useful.

Here is the PR with COURSE_CREATED signal only: https://github.com/Pearson-Advance/edx-platform/pull/109

2024-06-10 15:58 UTC, closed without merging