PAE-103 - Changes the text input  to a dropdown when the studio_home.enable_global_staff_optimization is activated
Pearson-Advance/edx-platform pull request #53
Opened 2021-09-21 13:29 UTC by elvinquero

Right now there is a Waffle Switch that when activated, it displays a text input to filter courses by org in the Studio Home page. The default behavior when no org is selected is to display the page without a single course.

This PR changes:
1) The text input is changed to a Dropdown. The **ORGANIZATION_APP** has to be activated in the CMS for it to recover all the orgs from discovery.

Guide to activate the dropdown:
1. Make sure the **ORGANIZATIONS_APP** is set to True on the FEATURES dict on edx-platform/cms/envs/common.py https://github.com/Pearson-Advance/edx-platform/blob/3792f3d740d76b245f7ff05492ede2ce9a637129/cms/envs/common.py#L283
2. Create and activate the **studio_home.enable_global_staff_optimization** Waffle Switch.

On the Stage and Production server, the organizations app will be activated through ANSIBLE variables, so there is no need to activated on the PR.

2021-09-21 14:22 UTC, Jacatove requested changes

2021-09-21 14:22 UTC, Jacatove commented on cms/envs/devstack.py
> +FEATURES.update({
@elvinquero I would put this here: https://github.com/Pearson-Advance/edx-platform/blob/3792f3d740d76b245f7ff05492ede2ce9a637129/cms/envs/common.py#L164
and keep in mind that you will need to set this variable in ansible in order to retrieve the variable in production, take a look at this: https://github.com/Pearson-Advance/edx-platform/blob/3792f3d740d76b245f7ff05492ede2ce9a637129/cms/envs/production.py#L273

2021-09-21 14:22 UTC, Jacatove commented on cms/djangoapps/contentstore/views/course.py
> +    org = selected_org if optimization_enabled and selected_org != '' else None
@elvinquero  What do you think about this?
```suggestion
    selected_org = request.GET.get('org', '')
    org = selected_org if optimization_enabled and selected_org else None
```
Is there a reason to validate that selected_org isn't empty?

2021-09-21 14:22 UTC, Jacatove commented on cms/djangoapps/contentstore/views/course.py
> +        u'org_names_list': org_names_list
@elvinquero Add a trailing comma.
```suggestion
        u'org_names_list': org_names_list,
```

2021-09-23 19:52 UTC, diegomillan approved these changes

2021-09-24 14:55 UTC, Jacatove requested changes

2021-09-24 15:05 UTC, elvinquero commented
On a local devstack, there is more than just one discovery. Localhost, discovery.main.localhost. The Studio app will bring the Orgs based on what Discovery is connected to. I believe that on stage and prod settings, just one discovery is used, so it won't cause a problem.

2021-09-24 16:16 UTC, elvinquero commented
As the ANSIBLE variables will override the default settings. There is no need to activate the ORGANIZATIONS_APP on this PR, however in order to test it, people will need set it to `True` on https://github.com/Pearson-Advance/edx-platform/blob/3792f3d740d76b245f7ff05492ede2ce9a637129/cms/envs/common.py#L283

2021-09-24 16:16 UTC, elvinquero commented on cms/envs/common.py
> +    'ORGANIZATIONS_APP': True,
Done! And I updated the PR description to let others know how to activate the filter feature.

2021-09-24 16:32 UTC, diegomillan approved these changes
Understood @elvinquero, ansible will handle the activation. Reapproved.

2021-09-24 16:37 UTC, Jacatove approved these changes

2021-10-01 14:40 UTC, Squirrel18 requested changes

2021-10-01 14:40 UTC, Squirrel18 commented on cms/djangoapps/contentstore/views/course.py
> +    org_names_list = [(org["short_name"]) for org in organizations]
Add a safe getter for "short_name". Also, do not mix single and double quotes. @elvinquero 
nit: you can remove this variable as it's only used once.

2021-10-01 14:40 UTC, Squirrel18 commented on cms/djangoapps/contentstore/views/course.py
> +
Unnecessary blank line. @elvinquero

2021-10-06 16:05 UTC, elvinquero commented
@Squirrel18 suggestions were applied.

2021-10-06 19:09 UTC, Squirrel18 requested changes

2021-10-07 13:14 UTC, merged