PADV-26 - Add license usage url to the data report context.
Pearson-Advance/edx-platform pull request #61
Opened 2021-11-05 04:01 UTC by ivanvgh

### Description:
This PR adds the license usage url with the course_id  to the data download section context, so when rendering the template the new button (Download license usage) will have the URL to trigger the action.

More context about the new button in [PADV-26 in openedx-themes](https://github.com/Pearson-Advance/openedx-themes/pull/186).

More context about the view that will have the logic in [PADV-26 course_operations plugin](https://github.com/Pearson-Advance/course_operations/pull/20).

2021-11-05 13:58 UTC, diegomillan approved these changes

2021-11-05 18:15 UTC, diegomillan approved these changes

2021-11-05 22:43 UTC, Squirrel18 requested changes

2021-11-05 22:43 UTC, Squirrel18 commented on lms/static/js/instructor_dashboard/data_download.js
> +                        errorMessage = error.responseText?JSON.parse(error.responseText):errorMessage
```suggestion
                        errorMessage = error.responseText ? JSON.parse(error.responseText) : errorMessage
```

2021-11-05 22:54 UTC, Squirrel18 approved these changes

2021-11-08 12:59 UTC, elvinquero approved these changes

2021-11-09 23:54 UTC, merged