PADV-144 - Do not add master course staff users to CCXs.
Pearson-Advance/edx-platform pull request #77
Opened 2022-07-28 19:20 UTC by Jacatove

## Description:

Once a CCX is created, then the `add_master_course_staff_to_ccx` function is called to add staff and instructor roles on ccx to all the staff and instructors members of master course. This is not convenient for our Course Licensing because it is not the desired behavior. Therefore, this PR is intended to changes the workflow of the ccx creation to stop the execution of `add_master_course_staff_to_ccx`.

## Testing Instruction:

2022-08-01 14:13 UTC, anfbermudezme approved these changes
LGTM.

2022-08-03 00:41 UTC, Squirrel18 requested changes

2022-08-03 00:41 UTC, Squirrel18 commented on lms/djangoapps/ccx/views.py
> +    is_course_licensing_enable = configuration_helpers.get_value('PCO_ENABLE_LICENSE_ENFORCEMENT', False)
Please, add a blank line after this line to separate assignment lines from action lines. @Jacatove

2022-08-03 15:54 UTC, Squirrel18 approved these changes

2022-08-03 16:09 UTC, merged