PADV-141 - feat: support feedback at enrollment section within CCX Coach Tab.
Pearson-Advance/edx-platform pull request #81
Opened 2022-09-05 22:02 UTC by Jacatove

## Description:

2022-09-06 20:15 UTC, anfbermudezme commented on lms/djangoapps/ccx/utils.py
> +                messages.add_message(
What do you think about moving the logic to calculate the error message to course_operations?

2022-09-06 20:15 UTC, anfbermudezme commented on lms/djangoapps/ccx/utils.py
> +        if is_course_licensing_enable and num_identifiers > 1:
Following the previous comment, what do you think about leaving the is_course_licensing_enable validation and moving the rest of the logic to the plugin?

2022-09-06 20:38 UTC, scottrish commented
@Jacatove just confirming that in each case, we will report the email/username of each successful and failed enrollment?

2022-09-06 21:03 UTC, Jacatove commented
@scottrish We are reporting only the email for successful enrollments. In case License limit is reached, we are not reporting emails which couldn't be enrolled, the license limit error message appears instead.

2022-09-13 13:37 UTC, anfbermudezme requested changes

2022-09-13 13:37 UTC, anfbermudezme commented on lms/djangoapps/ccx/utils.py
> +                allow_enrollment = run_extension_point(
`allow_enrollment` Variable used once.

```suggestion
                if is_course_licensing_enable and not must_enroll:
                  # Check the License limit in the pearson course operation plugin.
                  if not run_extension_point(
                      'PCO_ENFORCE_LICENSE_LIMITS',
                      course_key=course_key,
                      email=email,
                      student=student,
                      request=current_request,
                  ):
                      break
```

2022-09-14 15:17 UTC, anfbermudezme approved these changes

2022-09-16 01:46 UTC, alexjmpb approved these changes

2022-09-16 15:30 UTC, kuipumu approved these changes

2022-09-20 02:27 UTC, merged