PADV-214 add PCO_STUDENT_ADMIN_TRANSITION extension_point.
Pearson-Advance/edx-platform pull request #83
Opened 2022-09-19 18:09 UTC by anfbermudezme

## Ticket

https://agile-jira.pearson.com/browse/PADV-214

## Description
 
This PR add `PCO_STUDENT_ADMIN_TRANSITION` extension point to  to manage student and admin transitions for license enforcement in the Instructor Course Team Management table.

## PR's Related

### course_operations

- https://github.com/Pearson-Advance/course_operations/pull/121

## Type of Change

- [x] Add `PCO_STUDENT_ADMIN_TRANSITION`,  extension pont to manage student and admin transitions for license enforcement.

## Testing

- Follow the Testing Steps from https://github.com/Pearson-Advance/course_operations/pull/121

## Reviewers

- [ ] @Jacatove 
- [ ] @kuipumu

2022-09-20 00:36 UTC, Jacatove requested changes

2022-09-20 00:36 UTC, Jacatove commented on lms/djangoapps/instructor/views/api.py
> +    if run_extension_point('PCO_IS_LICENSED_CCX',course_id=course_id):
Let's check if course licensing is enable before calling anything. @anfbermudezme 
```suggestion
    if run_extension_point('PCO_ENABLE_COURSE_LICENSING'):
```

2022-09-20 00:36 UTC, Jacatove commented on lms/djangoapps/instructor/views/api.py
> +            rolename=rolename,
Let's ask our Product Owner what we should do for the other roles such as:
![image](https://user-images.githubusercontent.com/40271196/191140750-5fab79cf-e131-4ec7-8295-aeaad01d90f7.png)
@anfbermudezme

2022-09-21 23:59 UTC, anfbermudezme commented
We decided to use the signal receiver approach.

2022-09-21 23:59 UTC, closed without merging