feat: add sentry integration.
Pearson-Advance/edx-platform pull request #97
Opened 2023-05-18 19:31 UTC by Jacatove

## Description

This PR adds the Sentry integration to our platform.

**Note:** Requirements were updated manually in order to avoid changes in other packages. Our platform already meets the requirements for the sentry version used in this PR.

![image](https://github.com/Pearson-Advance/edx-platform/assets/40271196/80ba1307-0ddd-490d-a047-7968189f22e5)

- https://github.com/Pearson-Advance/edx-platform/blob/0c8ff45cf902734666f051f85ab1aea072ccde4f/requirements/edx/base.txt#L240

- https://github.com/Pearson-Advance/edx-platform/blob/0c8ff45cf902734666f051f85ab1aea072ccde4f/requirements/edx/base.txt#LL39C6-L39C6

Settings are defined here:  https://github.com/Pearson-Advance/edx-deployment-pe/commit/aa7a9fea0d35d35ae4b4c42384656f748b253961

2023-05-18 21:00 UTC, Squirrel18 requested changes

2023-05-18 21:00 UTC, Squirrel18 commented on lms/envs/production.py
> +    capture_message("Sentry integration - LMS")
Do not mix single and double quotes. @Jacatove

2023-05-19 03:52 UTC, Squirrel18 approved these changes

2023-05-19 11:05 UTC, anfbermudezme approved these changes

2023-05-19 14:09 UTC, merged