PADV 511 - Migrate Studio theme
Pearson-Advance/edx-platform pull request #98
Opened 2023-05-23 13:17 UTC by alexjmpb

## Ticket

https://agile-jira.pearson.com/browse/PADV-511

## Description

This PR aims to migrate the pearson-studio-theme to Olive. This adds the necessary context to the index.html template so the organization dropdown can get the organization list and apply the filter. This PR is related to this other in openedx-themes 

## Changes Made

- [x] Add organizations list context

## How to test

- Change to the branch vue/PADV-511 in your edx-platform
- Activate the studio_home.enable_global_staff_optimization waffle switch in the studio admin page
- Enable the ORGANIZATION_APP feature in Studio
- You should be able to access the org_names_list variable inside the index.html and should contain a list with the organizations
- To test you can enable the pearson-studio-theme and verify that the dropdown contains the sites created

## Reviewers

- [ ] @anfbermudezme 
- [ ] @kuipumu 
- [ ] @sergivalero20

2023-05-23 14:08 UTC, anfbermudezme commented
Why did you not cherry pick the commits for this feature?

- https://github.com/Pearson-Advance/edx-platform/pull/53
- https://github.com/Pearson-Advance/edx-platform/pull/56

2023-05-25 14:53 UTC, anfbermudezme requested changes

2023-05-25 14:53 UTC, anfbermudezme commented on cms/djangoapps/contentstore/views/course.py
> +        org_names_list = [(org['short_name']) for org in get_organizations() if 'short_name' in org]
Where is `get_organizations` defined?

2023-05-25 17:16 UTC, anfbermudezme approved these changes

2023-05-25 18:28 UTC, kuipumu approved these changes

2023-05-26 14:22 UTC, sergivalero20 approved these changes

2023-05-26 19:50 UTC, merged